spring:
  application:
    name: configserver
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/CandyPanda-LS/Hotel-Microservice.git"
          default-label: master
          search-paths: configs
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8071
