spring:
  application:
    name: configserver
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/CandyPanda-LS/Hotel-Microservice.git"
          default-label: master
          search-paths: configs
          timeout: 5
          clone-on-start: true
          force-pull: true
        encrypt:
          enabled: true
server:
  port: 8071

encrypt:
  key: "K9v$2bX!aP@7zQ#mR5y&C*dW4fE8nT"

management:
  endpoints:
    web:
      exposure:
        include: "*"