spring:
  application:
    name: reservation
  config:
    import: "configserver:http://localhost:8071"
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

