services:
  hotel:
    image: "lasalhettiarachchi/hotelms:s2"
    container_name: hotel-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hotelSystem
#    platform: linux/amd64
  user:
    image: "lasalhettiarachchi/userms:s2"
    container_name: user-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hotelSystem
#    platform: linux/amd64

networks:
  hotelSystem:
    driver: bridge
