spring:
  application:
    name: HotelService
  datasource:
    url: jdbc:postgresql://hotelmsdb.postgres.database.azure.com:5432/postgres
    username: hotadmin
    password: admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: hotel_db
server:
  port: 8081