server:
  port: 8070

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false #fetching details of other services from eureka server
    registerWithEureka: false #registering with eureka server
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

