spring:
  datasource:
    url: jdbc:postgresql://hotelmsdb.postgres.database.azure.com:5432/postgres
    username: "{cipher}fe19b893c0cebe27434c63477bfbeae81be508650dfccc1fbe4351d79c10ae36"
    password: "{cipher}45e6cdb2f3a985e3bb034ebdee122a63164cc4be8e88db8f3d918a14fc065ba7"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: hotel_db
server:
  port: 8082
