spring:
  datasource:
    url: jdbc:postgresql://hotelmsdb.postgres.database.azure.com:5432/postgres
    username: "{cipher}188be752197f82d11b4e0575a32de7d470e9c219277c3f7a0b58a524b765aed8"
    password: "{cipher}2db4524e223b47335316f88594614de0ec1e772820d7516b1375b70c4e2178d1"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: reservation_db
server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "reservation"
    description: "Reservation Service"
    version: 1.0.0